/* eslint-disable */
// Generated file — do not edit. Regenerate with `npm run model:codegen`.
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/hero.glb --types --keepnames --root public/ --output src/components/three/hero/HeroModel.generated.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import type { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    monitor1: THREE.Mesh
    podstawka1: THREE.Mesh
    screen1: THREE.Mesh
    monitor2: THREE.Mesh
    podstawka2: THREE.Mesh
    screen2: THREE.Mesh
    notebook: THREE.Mesh
    page_bottom_left: THREE.Mesh
    page_bottom_right: THREE.Mesh
    page_left: THREE.Mesh
    page_right: THREE.Mesh
    page_top_left: THREE.Mesh
    page_top_right: THREE.Mesh
    macbook: THREE.Mesh
    iphone: THREE.Mesh
    pen: THREE.Mesh
    paper: THREE.Mesh
    printer: THREE.Mesh
    wall: THREE.Mesh
    desk_top: THREE.Mesh
    desk_light_blocker: THREE.Mesh
    chair_bottom: THREE.Mesh
    chair_back: THREE.Mesh
    chair_arms: THREE.Mesh
    chair_mesh: THREE.Mesh
    chair_seat: THREE.Mesh
    chair_wheels: THREE.Mesh
    mug: THREE.Mesh
    coffee: THREE.Mesh
    mousepad: THREE.Mesh
    microphone: THREE.Mesh
    mouse: THREE.Mesh
    headphones: THREE.Mesh
    webcam: THREE.Mesh
    Apple_MK_buttons: THREE.Mesh
    Apple_MK_power: THREE.Mesh
    macstudio: THREE.Mesh
    macstudio_light: THREE.Mesh
  }
  materials: {}
  animations: THREE.AnimationClip[]
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/model/hero.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="printer_empty" position={[-0.336, 0.75, 0.273]} rotation={[Math.PI / 2, 0, 0]} scale={0.019}>
        <mesh name="paper" geometry={nodes.paper.geometry} material={nodes.paper.material} position={[0, 0.165, 0]} scale={[1.25, 1, 1]} />
        <mesh name="printer" geometry={nodes.printer.geometry} material={nodes.printer.material} />
      </group>
      <PerspectiveCamera name="Camera" makeDefault={false} far={1000} near={0.1} fov={22.895} position={[0.083, 1.43, 3.401]} rotation={[-0.139, -0.09, -0.013]} scale={0.417} />
      <mesh name="wall" geometry={nodes.wall.geometry} material={nodes.wall.material} />
      <mesh name="desk_top" geometry={nodes.desk_top.geometry} material={nodes.desk_top.material} />
      <mesh name="desk_light_blocker" geometry={nodes.desk_light_blocker.geometry} material={nodes.desk_light_blocker.material} />
      <mesh name="chair_bottom" geometry={nodes.chair_bottom.geometry} material={nodes.chair_bottom.material} position={[0.792, 0.269, 0.966]}>
        <mesh name="chair_back" geometry={nodes.chair_back.geometry} material={nodes.chair_back.material} position={[-0.792, -0.269, -0.966]}>
          <mesh name="chair_arms" geometry={nodes.chair_arms.geometry} material={nodes.chair_arms.material} />
          <mesh name="chair_mesh" geometry={nodes.chair_mesh.geometry} material={nodes.chair_mesh.material} />
          <mesh name="chair_seat" geometry={nodes.chair_seat.geometry} material={nodes.chair_seat.material} />
        </mesh>
      </mesh>
      <mesh name="chair_wheels" geometry={nodes.chair_wheels.geometry} material={nodes.chair_wheels.material} />
      <mesh name="mug" geometry={nodes.mug.geometry} material={nodes.mug.material} />
      <mesh name="coffee" geometry={nodes.coffee.geometry} material={nodes.coffee.material} />
      <mesh name="mousepad" geometry={nodes.mousepad.geometry} material={nodes.mousepad.material} />
      <mesh name="microphone" geometry={nodes.microphone.geometry} material={nodes.microphone.material} />
      <mesh name="mouse" geometry={nodes.mouse.geometry} material={nodes.mouse.material} />
      <mesh name="headphones" geometry={nodes.headphones.geometry} material={nodes.headphones.material} />
      <mesh name="webcam" geometry={nodes.webcam.geometry} material={nodes.webcam.material} />
      <mesh name="Apple_MK_buttons" geometry={nodes.Apple_MK_buttons.geometry} material={nodes.Apple_MK_buttons.material} />
      <mesh name="Apple_MK_power" geometry={nodes.Apple_MK_power.geometry} material={nodes.Apple_MK_power.material} />
      <mesh name="macstudio" geometry={nodes.macstudio.geometry} material={nodes.macstudio.material}>
        <mesh name="macstudio_light" geometry={nodes.macstudio_light.geometry} material={nodes.macstudio_light.material} />
      </mesh>
      <mesh name="monitor1" geometry={nodes.monitor1.geometry} material={nodes.monitor1.material} />
      <mesh name="podstawka1" geometry={nodes.podstawka1.geometry} material={nodes.podstawka1.material} />
      <mesh name="screen1" geometry={nodes.screen1.geometry} material={nodes.screen1.material} position={[0.321, 1.067, 0.328]} />
      <mesh name="monitor2" geometry={nodes.monitor2.geometry} material={nodes.monitor2.material} />
      <mesh name="podstawka2" geometry={nodes.podstawka2.geometry} material={nodes.podstawka2.material} />
      <mesh name="screen2" geometry={nodes.screen2.geometry} material={nodes.screen2.material} position={[0.924, 1.067, 0.403]} />
      <mesh name="notebook" geometry={nodes.notebook.geometry} material={nodes.notebook.material}>
        <mesh name="page_bottom_left" geometry={nodes.page_bottom_left.geometry} material={nodes.page_bottom_left.material} />
        <mesh name="page_bottom_right" geometry={nodes.page_bottom_right.geometry} material={nodes.page_bottom_right.material} />
        <mesh name="page_left" geometry={nodes.page_left.geometry} material={nodes.page_left.material} />
        <mesh name="page_right" geometry={nodes.page_right.geometry} material={nodes.page_right.material} />
        <mesh name="page_top_left" geometry={nodes.page_top_left.geometry} material={nodes.page_top_left.material} />
        <mesh name="page_top_right" geometry={nodes.page_top_right.geometry} material={nodes.page_top_right.material} />
      </mesh>
      <mesh name="macbook" geometry={nodes.macbook.geometry} material={nodes.macbook.material} />
      <mesh name="iphone" geometry={nodes.iphone.geometry} material={nodes.iphone.material} />
      <mesh name="pen" geometry={nodes.pen.geometry} material={nodes.pen.material} />
    </group>
  )
}

useGLTF.preload('/model/hero.glb')
