// Auto-generates src/styles/tokens.generated.css from src/theme/tokens.json.
// Runs via npm `predev` and `prebuild` hooks — never edit the generated file by hand.

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const TOKENS_PATH = resolve(ROOT, "src/theme/tokens.json");
const OUT_PATH = resolve(ROOT, "src/styles/tokens.generated.css");

const tokens = JSON.parse(readFileSync(TOKENS_PATH, "utf8"));

const camelToKebab = (s) => s.replace(/([A-Z])/g, "-$1").toLowerCase();

const tokenLines = [];

for (const [key, value] of Object.entries(tokens.colors)) {
  tokenLines.push(`  --color-tm-${camelToKebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(tokens.radius)) {
  tokenLines.push(`  --radius-tm-${camelToKebab(key)}: ${value};`);
}
for (const [key, value] of Object.entries(tokens.shadow)) {
  tokenLines.push(`  --shadow-tm-${camelToKebab(key)}: ${value};`);
}
if (tokens.font) {
  for (const [key, value] of Object.entries(tokens.font)) {
    tokenLines.push(`  --font-tm-${camelToKebab(key)}: ${value};`);
  }
}

const lines = [];
lines.push("/*");
lines.push(" * AUTO-GENERATED by scripts/sync-tokens.mjs.");
lines.push(" * Source of truth: src/theme/tokens.json — DO NOT EDIT THIS FILE.");
lines.push(" */");
lines.push("");
lines.push("@theme {");
lines.push(...tokenLines);
lines.push("}");
lines.push("");
lines.push("/* Runtime CSS custom properties for SCSS modules and browser styles. */");
lines.push(":root {");
lines.push(...tokenLines);
lines.push("");
lines.push("  /* Derived (composes vars defined above). */");
lines.push(
  "  --color-tm-blue-gradient: linear-gradient(135deg, var(--color-tm-navy-dark) 0%, var(--color-tm-blue) 52%, var(--color-tm-green) 100%);",
);
lines.push(
  "  --color-tm-blue-gradient-dark: linear-gradient(to bottom right in oklab, var(--color-tm-navy-dark) 0%, var(--color-tm-blue) 52%, var(--color-tm-green) 100%);",
);
lines.push("}");
lines.push("");

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, lines.join("\n"), "utf8");

console.log(`✓ tokens synced → ${OUT_PATH.replace(ROOT + "/", "")}`);
